name: Build and publish release packages
permissions:
  contents: write
on:
  release:
    # 'published' is triggered when publishing draft release, 'created' is not
    types: [published]

jobs:
  build-windows-binaries:
    strategy:
      matrix:
        include:
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          RUSTFLAGS: -C target-cpu=core-avx2 -C target-feature=-avx512f
        run: cargo build --release --locked --target=x86_64-pc-windows-msvc

      - name: Package binary (zip)
        run: |
          Compress-Archive -Path "target\x86_64-pc-windows-msvc\release\qdrant.exe" -DestinationPath "qdrant-windows-x64.zip" -CompressionLevel Optimal

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: qdrant-windows-x64.zip
